//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryGame.MemoryGameService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MemoryGameService.IMemoryGameService")]
    public interface IMemoryGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemoryGameService/startSession", ReplyAction="http://tempuri.org/IMemoryGameService/startSessionResponse")]
        void startSession();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMemoryGameService/startSession", ReplyAction="http://tempuri.org/IMemoryGameService/startSessionResponse")]
        System.Threading.Tasks.Task startSessionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemoryGameServiceChannel : MemoryGame.MemoryGameService.IMemoryGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemoryGameServiceClient : System.ServiceModel.ClientBase<MemoryGame.MemoryGameService.IMemoryGameService>, MemoryGame.MemoryGameService.IMemoryGameService {
        
        public MemoryGameServiceClient() {
        }
        
        public MemoryGameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemoryGameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemoryGameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemoryGameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void startSession() {
            base.Channel.startSession();
        }
        
        public System.Threading.Tasks.Task startSessionAsync() {
            return base.Channel.startSessionAsync();
        }
    }
}
