namespace DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ChangedAutogeneratedKeyProperty : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Cards", "CardDeckId", "dbo.CardDecks");
            DropForeignKey("dbo.Matches", "CardDeckId", "dbo.CardDecks");
            DropForeignKey("dbo.MatchesPlayed", "MatchId", "dbo.Matches");
            DropForeignKey("dbo.Winners", "MatchId", "dbo.Matches");
            DropPrimaryKey("dbo.CardDecks");
            DropPrimaryKey("dbo.Cards");
            DropPrimaryKey("dbo.Matches");
            AlterColumn("dbo.CardDecks", "CardDeckId", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Cards", "CardId", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Matches", "MatchId", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("dbo.CardDecks", "CardDeckId");
            AddPrimaryKey("dbo.Cards", "CardId");
            AddPrimaryKey("dbo.Matches", "MatchId");
            AddForeignKey("dbo.Cards", "CardDeckId", "dbo.CardDecks", "CardDeckId");
            AddForeignKey("dbo.Matches", "CardDeckId", "dbo.CardDecks", "CardDeckId");
            AddForeignKey("dbo.MatchesPlayed", "MatchId", "dbo.Matches", "MatchId", cascadeDelete: true);
            AddForeignKey("dbo.Winners", "MatchId", "dbo.Matches", "MatchId");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Winners", "MatchId", "dbo.Matches");
            DropForeignKey("dbo.MatchesPlayed", "MatchId", "dbo.Matches");
            DropForeignKey("dbo.Matches", "CardDeckId", "dbo.CardDecks");
            DropForeignKey("dbo.Cards", "CardDeckId", "dbo.CardDecks");
            DropPrimaryKey("dbo.Matches");
            DropPrimaryKey("dbo.Cards");
            DropPrimaryKey("dbo.CardDecks");
            AlterColumn("dbo.Matches", "MatchId", c => c.Int(nullable: false));
            AlterColumn("dbo.Cards", "CardId", c => c.Int(nullable: false));
            AlterColumn("dbo.CardDecks", "CardDeckId", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.Matches", "MatchId");
            AddPrimaryKey("dbo.Cards", "CardId");
            AddPrimaryKey("dbo.CardDecks", "CardDeckId");
            AddForeignKey("dbo.Winners", "MatchId", "dbo.Matches", "MatchId");
            AddForeignKey("dbo.MatchesPlayed", "MatchId", "dbo.Matches", "MatchId", cascadeDelete: true);
            AddForeignKey("dbo.Matches", "CardDeckId", "dbo.CardDecks", "CardDeckId");
            AddForeignKey("dbo.Cards", "CardDeckId", "dbo.CardDecks", "CardDeckId");
        }
    }
}
