//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryGame.Proxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IAccessibilityService")]
    public interface IAccessibilityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessibilityService/HasAccessRights", ReplyAction="http://tempuri.org/IAccessibilityService/HasAccessRightsResponse")]
        bool HasAccessRights(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessibilityService/HasAccessRights", ReplyAction="http://tempuri.org/IAccessibilityService/HasAccessRightsResponse")]
        System.Threading.Tasks.Task<bool> HasAccessRightsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessibilityService/RegisterNewPlayer", ReplyAction="http://tempuri.org/IAccessibilityService/RegisterNewPlayerResponse")]
        bool RegisterNewPlayer(string emailAddress, string username, string password, string verificationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessibilityService/RegisterNewPlayer", ReplyAction="http://tempuri.org/IAccessibilityService/RegisterNewPlayerResponse")]
        System.Threading.Tasks.Task<bool> RegisterNewPlayerAsync(string emailAddress, string username, string password, string verificationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessibilityService/EmailAddressIsAvailable", ReplyAction="http://tempuri.org/IAccessibilityService/EmailAddressIsAvailableResponse")]
        bool EmailAddressIsAvailable(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessibilityService/EmailAddressIsAvailable", ReplyAction="http://tempuri.org/IAccessibilityService/EmailAddressIsAvailableResponse")]
        System.Threading.Tasks.Task<bool> EmailAddressIsAvailableAsync(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessibilityService/UserNameIsAvailable", ReplyAction="http://tempuri.org/IAccessibilityService/UserNameIsAvailableResponse")]
        bool UserNameIsAvailable(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessibilityService/UserNameIsAvailable", ReplyAction="http://tempuri.org/IAccessibilityService/UserNameIsAvailableResponse")]
        System.Threading.Tasks.Task<bool> UserNameIsAvailableAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessibilityService/VerifyToken", ReplyAction="http://tempuri.org/IAccessibilityService/VerifyTokenResponse")]
        bool VerifyToken(string emailAddress, string verificationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessibilityService/VerifyToken", ReplyAction="http://tempuri.org/IAccessibilityService/VerifyTokenResponse")]
        System.Threading.Tasks.Task<bool> VerifyTokenAsync(string emailAddress, string verificationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessibilityService/SetAccountAsVerified", ReplyAction="http://tempuri.org/IAccessibilityService/SetAccountAsVerifiedResponse")]
        bool SetAccountAsVerified(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessibilityService/SetAccountAsVerified", ReplyAction="http://tempuri.org/IAccessibilityService/SetAccountAsVerifiedResponse")]
        System.Threading.Tasks.Task<bool> SetAccountAsVerifiedAsync(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessibilityService/AssignNewVerificationToken", ReplyAction="http://tempuri.org/IAccessibilityService/AssignNewVerificationTokenResponse")]
        bool AssignNewVerificationToken(string emailAddress, string verificationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccessibilityService/AssignNewVerificationToken", ReplyAction="http://tempuri.org/IAccessibilityService/AssignNewVerificationTokenResponse")]
        System.Threading.Tasks.Task<bool> AssignNewVerificationTokenAsync(string emailAddress, string verificationToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccessibilityServiceChannel : MemoryGame.Proxy.IAccessibilityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccessibilityServiceClient : System.ServiceModel.ClientBase<MemoryGame.Proxy.IAccessibilityService>, MemoryGame.Proxy.IAccessibilityService {
        
        public AccessibilityServiceClient() {
        }
        
        public AccessibilityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccessibilityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessibilityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccessibilityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool HasAccessRights(string username, string password) {
            return base.Channel.HasAccessRights(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> HasAccessRightsAsync(string username, string password) {
            return base.Channel.HasAccessRightsAsync(username, password);
        }
        
        public bool RegisterNewPlayer(string emailAddress, string username, string password, string verificationToken) {
            return base.Channel.RegisterNewPlayer(emailAddress, username, password, verificationToken);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterNewPlayerAsync(string emailAddress, string username, string password, string verificationToken) {
            return base.Channel.RegisterNewPlayerAsync(emailAddress, username, password, verificationToken);
        }
        
        public bool EmailAddressIsAvailable(string emailAddress) {
            return base.Channel.EmailAddressIsAvailable(emailAddress);
        }
        
        public System.Threading.Tasks.Task<bool> EmailAddressIsAvailableAsync(string emailAddress) {
            return base.Channel.EmailAddressIsAvailableAsync(emailAddress);
        }
        
        public bool UserNameIsAvailable(string username) {
            return base.Channel.UserNameIsAvailable(username);
        }
        
        public System.Threading.Tasks.Task<bool> UserNameIsAvailableAsync(string username) {
            return base.Channel.UserNameIsAvailableAsync(username);
        }
        
        public bool VerifyToken(string emailAddress, string verificationToken) {
            return base.Channel.VerifyToken(emailAddress, verificationToken);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyTokenAsync(string emailAddress, string verificationToken) {
            return base.Channel.VerifyTokenAsync(emailAddress, verificationToken);
        }
        
        public bool SetAccountAsVerified(string emailAddress) {
            return base.Channel.SetAccountAsVerified(emailAddress);
        }
        
        public System.Threading.Tasks.Task<bool> SetAccountAsVerifiedAsync(string emailAddress) {
            return base.Channel.SetAccountAsVerifiedAsync(emailAddress);
        }
        
        public bool AssignNewVerificationToken(string emailAddress, string verificationToken) {
            return base.Channel.AssignNewVerificationToken(emailAddress, verificationToken);
        }
        
        public System.Threading.Tasks.Task<bool> AssignNewVerificationTokenAsync(string emailAddress, string verificationToken) {
            return base.Channel.AssignNewVerificationTokenAsync(emailAddress, verificationToken);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.ICommunicationService")]
    public interface ICommunicationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunicationService/SendMessage", ReplyAction="http://tempuri.org/ICommunicationService/SendMessageResponse")]
        void SendMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunicationService/SendMessage", ReplyAction="http://tempuri.org/ICommunicationService/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunicationService/GetMessage", ReplyAction="http://tempuri.org/ICommunicationService/GetMessageResponse")]
        string GetMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommunicationService/GetMessage", ReplyAction="http://tempuri.org/ICommunicationService/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommunicationServiceChannel : MemoryGame.Proxy.ICommunicationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommunicationServiceClient : System.ServiceModel.ClientBase<MemoryGame.Proxy.ICommunicationService>, MemoryGame.Proxy.ICommunicationService {
        
        public CommunicationServiceClient() {
        }
        
        public CommunicationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommunicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMessage(string message) {
            base.Channel.SendMessage(message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string message) {
            return base.Channel.SendMessageAsync(message);
        }
        
        public string GetMessage() {
            return base.Channel.GetMessage();
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync() {
            return base.Channel.GetMessageAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IMemoryGameService", CallbackContract=typeof(MemoryGame.Proxy.IMemoryGameServiceCallback))]
    public interface IMemoryGameService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMemoryGameService/GetActivePlayers")]
        void GetActivePlayers();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMemoryGameService/GetActivePlayers")]
        System.Threading.Tasks.Task GetActivePlayersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemoryGameServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMemoryGameService/ShowActivePlayers")]
        void ShowActivePlayers(string[] activePlayers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemoryGameServiceChannel : MemoryGame.Proxy.IMemoryGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemoryGameServiceClient : System.ServiceModel.DuplexClientBase<MemoryGame.Proxy.IMemoryGameService>, MemoryGame.Proxy.IMemoryGameService {
        
        public MemoryGameServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MemoryGameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MemoryGameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MemoryGameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MemoryGameServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetActivePlayers() {
            base.Channel.GetActivePlayers();
        }
        
        public System.Threading.Tasks.Task GetActivePlayersAsync() {
            return base.Channel.GetActivePlayersAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IMailingService")]
    public interface IMailingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingService/SendVerificationToken", ReplyAction="http://tempuri.org/IMailingService/SendVerificationTokenResponse")]
        void SendVerificationToken(string name, string emailAddress, string verificationToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMailingService/SendVerificationToken", ReplyAction="http://tempuri.org/IMailingService/SendVerificationTokenResponse")]
        System.Threading.Tasks.Task SendVerificationTokenAsync(string name, string emailAddress, string verificationToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMailingServiceChannel : MemoryGame.Proxy.IMailingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailingServiceClient : System.ServiceModel.ClientBase<MemoryGame.Proxy.IMailingService>, MemoryGame.Proxy.IMailingService {
        
        public MailingServiceClient() {
        }
        
        public MailingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendVerificationToken(string name, string emailAddress, string verificationToken) {
            base.Channel.SendVerificationToken(name, emailAddress, verificationToken);
        }
        
        public System.Threading.Tasks.Task SendVerificationTokenAsync(string name, string emailAddress, string verificationToken) {
            return base.Channel.SendVerificationTokenAsync(name, emailAddress, verificationToken);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.ITokenGenerator")]
    public interface ITokenGenerator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenGenerator/GenerateToken", ReplyAction="http://tempuri.org/ITokenGenerator/GenerateTokenResponse")]
        string GenerateToken(int length);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITokenGenerator/GenerateToken", ReplyAction="http://tempuri.org/ITokenGenerator/GenerateTokenResponse")]
        System.Threading.Tasks.Task<string> GenerateTokenAsync(int length);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITokenGeneratorChannel : MemoryGame.Proxy.ITokenGenerator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TokenGeneratorClient : System.ServiceModel.ClientBase<MemoryGame.Proxy.ITokenGenerator>, MemoryGame.Proxy.ITokenGenerator {
        
        public TokenGeneratorClient() {
        }
        
        public TokenGeneratorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TokenGeneratorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenGeneratorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TokenGeneratorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GenerateToken(int length) {
            return base.Channel.GenerateToken(length);
        }
        
        public System.Threading.Tasks.Task<string> GenerateTokenAsync(int length) {
            return base.Channel.GenerateTokenAsync(length);
        }
    }
}
